// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8Hj4K5rPn8hGaEmE1n-9ae4YEHksfGU',
    appId: '1:161732335534:web:c67cc03d35009c8892da3f',
    messagingSenderId: '161732335534',
    projectId: 'food-delivery-app-8e1c0',
    authDomain: 'food-delivery-app-8e1c0.firebaseapp.com',
    storageBucket: 'food-delivery-app-8e1c0.appspot.com',
    measurementId: 'G-V3TTZZ07K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoQ9HeRIVYpnHYn6haMLAMDOCE4pPAwDU',
    appId: '1:161732335534:android:0ec391f6e37fbe5392da3f',
    messagingSenderId: '161732335534',
    projectId: 'food-delivery-app-8e1c0',
    storageBucket: 'food-delivery-app-8e1c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1zdAeGWDXJw0yM8F7C6ielHWt3A58BCQ',
    appId: '1:161732335534:ios:356b429167035caf92da3f',
    messagingSenderId: '161732335534',
    projectId: 'food-delivery-app-8e1c0',
    storageBucket: 'food-delivery-app-8e1c0.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1zdAeGWDXJw0yM8F7C6ielHWt3A58BCQ',
    appId: '1:161732335534:ios:356b429167035caf92da3f',
    messagingSenderId: '161732335534',
    projectId: 'food-delivery-app-8e1c0',
    storageBucket: 'food-delivery-app-8e1c0.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs8Hj4K5rPn8hGaEmE1n-9ae4YEHksfGU',
    appId: '1:161732335534:web:d7cb8d66fbdd510b92da3f',
    messagingSenderId: '161732335534',
    projectId: 'food-delivery-app-8e1c0',
    authDomain: 'food-delivery-app-8e1c0.firebaseapp.com',
    storageBucket: 'food-delivery-app-8e1c0.appspot.com',
    measurementId: 'G-M7VSZCVQT2',
  );
}
